- name: Compile
  id: build-packages
  uses: love-action/love-actions-macos-portable@v1
  with:
    app-name: "Lua Love Platformer"
    bundle-id: "com.MunaAlaneme.LuaLovePlatformer"
    copyright: "Copyright © 2020-2024 Morphed Armor All Rights Reserved."
    icon-path: ./assets/img/raster/emoji_u274c2.png
    love-ref: "fc3f5ee6209a0aab9a4d381ed5cd99110f9ff2f2"
    love-patch: "./love.patch"
    love-package: "./game.love"
    libs-path: ./libs
    extra-assets: ./README.md ./license.txt
    product-name: "my_game"
    version-string: "0.0.1"
    output-folder: "./dist"
    account-username: ${{ secrets.APPLE_ACCOUNT_USERNAME }}
    account-password: ${{ secrets.APPLE_ACCOUNT_PASSWORD }}
    developer-id-application-base64: ${{ secrets.APPLE_CERT_DEVELOPER_ID_APPLICATION }}
    developer-id-application-password: ${{ secrets.APPLE_CERT_DEVELOPER_ID_APPLICATION_PWD }}
    team-id: "${{ secrets.APPLE_DEVELOPER_TEAM_ID }}"
    developer-id-installer-base64: ${{ secrets.APPLE_CERT_DEVELOPER_ID_INSTALLER }}
    developer-id-installer-password: ${{ secrets.APPLE_CERT_DEVELOPER_ID_INSTALLER_PWD }}
    dmg-background-path: ./assets/macOS/dmg.png
    dmg-icon-position: "287 313"
    dmg-icon-size: "128"
    dmg-link-position: "734 313"
    dmg-text-size: "12"
    dmg-volume-icon-path: ./assets/macOS/dmg.icns
    dmg-volume-name: "LuaLovePlatformer"
    dmg-window-position: "200 120"
    dmg-window-size: "1280 720"
