name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#  workflow_dispatch:
#    inputs:
#      chosen-os:
#        required: true
#        type: choice
#        options:
#        - Ubuntu
#        - macOS
#        - Windows

jobs:
  test:
    #runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    runs-on: macos-latest

    - name: no
      run: --check-lua-versions

    steps:
    - uses: actions/checkout@master
    - uses: ilammy/msvc-dev-cmd@v1

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4.7"

    - uses: leafo/gh-actions-luarocks@v4

    - name: build
      run: |
        luarocks install busted
        luarocks install torch
        luarocks make rocks/nn-scm-1.rockspec

    - name: test
      run: |
        busted -o utfTerminal
